<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sangam Patil">
<meta name="dcterms.date" content="2025-04-18">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="homework_4_files/libs/clipboard/clipboard.min.js"></script>
<script src="homework_4_files/libs/quarto-html/quarto.js"></script>
<script src="homework_4_files/libs/quarto-html/popper.min.js"></script>
<script src="homework_4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="homework_4_files/libs/quarto-html/anchor.min.js"></script>
<link href="homework_4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="homework_4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="homework_4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="homework_4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="homework_4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 4</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sangam Patil </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 18, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'alr4'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'smss'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ dplyr::recode() masks car::recode()
✖ purrr::some()   masks car::some()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<section id="a" class="level6">
<h6 class="anchored" data-anchor-id="a">A</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>house_price_model <span class="ot">&lt;-</span> <span class="cf">function</span>(x1, x2, actual_price) {</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  predicted_price <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="dv">15000</span> <span class="sc">+</span> <span class="dv">25000</span> <span class="sc">*</span> x1 <span class="sc">+</span> <span class="dv">15000</span> <span class="sc">*</span> x2)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  residual <span class="ot">&lt;-</span> actual_price <span class="sc">-</span> predicted_price</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(predicted_price, residual))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">house_price_model</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">160000</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"For a home with 3 bedrooms and 2 bathrooms sold for $160,000:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "For a home with 3 bedrooms and 2 bathrooms sold for $160,000:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Predicted Value: "</span>, A[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Predicted Value:  90000"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Residual Value: "</span>, A[<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Residual Value:  70000"</code></pre>
</div>
</div>
<p>The model underestimated the price by $70,000 for this home. This means the actual selling price was significantly higher than what the model expected based on bedrooms and bathrooms alone.</p>
</section>
<section id="b" class="level6">
<h6 class="anchored" data-anchor-id="b">B</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>){</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">house_price_model</span>(i, <span class="dv">2</span>, <span class="dv">0</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Predicted Price for"</span>, i, <span class="st">"bedrooms and 2 bathrooms : "</span>, p[<span class="dv">1</span>]))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Predicted Price for 1 bedrooms and 2 bathrooms :  40000"
[1] "Predicted Price for 2 bedrooms and 2 bathrooms :  65000"
[1] "Predicted Price for 3 bedrooms and 2 bathrooms :  90000"
[1] "Predicted Price for 4 bedrooms and 2 bathrooms :  115000"
[1] "Predicted Price for 5 bedrooms and 2 bathrooms :  140000"
[1] "Predicted Price for 6 bedrooms and 2 bathrooms :  165000"
[1] "Predicted Price for 7 bedrooms and 2 bathrooms :  190000"
[1] "Predicted Price for 8 bedrooms and 2 bathrooms :  215000"
[1] "Predicted Price for 9 bedrooms and 2 bathrooms :  240000"
[1] "Predicted Price for 10 bedrooms and 2 bathrooms :  265000"</code></pre>
</div>
</div>
<p>Interpretation: 1. Each additional bedroom (holding bathrooms constant at 2) increases the predicted selling price by about $25,000. 2. This suggests a linear relationship between number of bedrooms and selling price when bathrooms are held constant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="dv">5</span>, <span class="fl">0.5</span>)){</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">house_price_model</span>(<span class="dv">3</span>, i, <span class="dv">0</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Predicted Price for 3 bedrooms and"</span>, i, <span class="st">"bathrooms : "</span>, p[<span class="dv">1</span>]))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Predicted Price for 3 bedrooms and 0.5 bathrooms :  67500"
[1] "Predicted Price for 3 bedrooms and 1 bathrooms :  75000"
[1] "Predicted Price for 3 bedrooms and 1.5 bathrooms :  82500"
[1] "Predicted Price for 3 bedrooms and 2 bathrooms :  90000"
[1] "Predicted Price for 3 bedrooms and 2.5 bathrooms :  97500"
[1] "Predicted Price for 3 bedrooms and 3 bathrooms :  105000"
[1] "Predicted Price for 3 bedrooms and 3.5 bathrooms :  112500"
[1] "Predicted Price for 3 bedrooms and 4 bathrooms :  120000"
[1] "Predicted Price for 3 bedrooms and 4.5 bathrooms :  127500"
[1] "Predicted Price for 3 bedrooms and 5 bathrooms :  135000"</code></pre>
</div>
</div>
<p>Interpretation: 1. Each additional half bathroom increases the predicted price by $7,500. 2. Again, we see a consistent, linear pattern.</p>
</section>
<section id="c" class="level6">
<h6 class="anchored" data-anchor-id="c">C</h6>
<p>Here: 1. One additional bedroom increases the price by $25,000. 2. One additional half bathroom increases the price by $7,500.</p>
<p>So, to match the $25,000 impact of one bedroom, we divide: 25,000 / 7,500 = 3.33</p>
<p>So, to have the same impact on selling price as adding one bedroom, you would need to add approximately 3.33 half bathrooms — or 1.67 full bathrooms (since 2 half baths = 1 full bath). Thus, about 1.67 (approx 2) full bathrooms are needed to match the price increase of one bedroom, assuming a linear relationship and other features held constant.</p>
</section>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"salary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="a-1" class="level6">
<h6 class="anchored" data-anchor-id="a-1">A</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">filter</span>(salary, sex <span class="sc">==</span> <span class="st">"Male"</span>), <span class="at">Avg_Salary_Male =</span> <span class="fu">mean</span>(salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Avg_Salary_Male
1        24696.79</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">filter</span>(salary, sex <span class="sc">==</span> <span class="st">"Female"</span>), <span class="at">Avg_Salary_Female =</span> <span class="fu">mean</span>(salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Avg_Salary_Female
1          21357.14</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, salary)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We are testing: 1. Null hypothesis (H₀): Mean salary for men = Mean salary for women 2. Alternative hypothesis (H₁): Mean salary for men ≠ Mean salary for women</p>
<p>This checks whether the difference in mean salaries between men and women is statistically significant, without adjusting for any other variable. If the sexFemale coefficient is significant (p-value &lt; 0.05), we reject the null and say that sex is associated with salary. This tells us that women earn on average $1166 more than men, after controlling for degree, rank, year, and years since degree. However, the p-value = 0.214, which is not statistically significant at the 0.05 level. So we fail to reject the null hypothesis. There is no strong evidence that men and women have different salaries after accounting for other variables.</p>
</section>
<section id="b-1" class="level6">
<h6 class="anchored" data-anchor-id="b-1">B</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, salary)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 14134.4059 17357.68946
degreePhD    -663.2482  3440.47485
rankAssoc    2985.4107  7599.31080
rankProf     8396.1546 13841.37340
sexFemale    -697.8183  3030.56452
year          285.1433   667.47476
ysdeg        -280.6397    31.49105</code></pre>
</div>
</div>
</section>
<section id="c-1" class="level6">
<h6 class="anchored" data-anchor-id="c-1">C</h6>
<ol type="1">
<li><p>Intercept: 21,038.41 • Statistical Significance: Highly significant (p &lt; 2e-16) • Interpretation: The baseline salary for an Assistant Professor with a Master’s degree, Male, with 0 years in rank and 0 years since degree. This value sets the foundation from which other effects are added or subtracted.</p></li>
<li><p>degreePhD: 1,388.61 • Statistical Significance: Not significant (p = 0.180, 95% CI includes 0) • Interpretation: On average, holding all else constant, faculty with a PhD earn $1,388 more than those with a Master’s degree. However, since the result is not statistically significant, we cannot confidently say this difference is real.</p></li>
<li><p>rankAsst: –5,292.36 • Statistical Significance: Significant (p &lt; 0.001) • Interpretation: Compared to Associate Professors (reference group), Assistant Professors earn about $5,292 less, all else held constant. This confirms the expected salary increase with rank progression.</p></li>
<li><p>rankProf: 5,826.40 • Statistical Significance: Significant (p &lt; 0.001) • Interpretation: Full Professors earn about $5,826 more than Associate Professors (reference group), holding all other variables constant. A clear and significant promotion-related salary bump.</p></li>
<li><p>sexFemale: 1,166.37 • Statistical Significance: Not significant (p = 0.214, CI includes 0) • Interpretation: Female faculty earn approximately $1,166 more than males, but this difference is not statistically significant. So, we do not find evidence of a salary difference by gender after controlling for education, rank, and experience.</p></li>
<li><p>year (Years in Rank): 476.31 • Statistical Significance: Significant (p &lt; 0.001) • Interpretation: For every additional year in the current rank, salary increases by $476 on average. Experience within rank is associated with salary growth.</p></li>
<li><p>ysdeg (Years Since Degree): –124.57 • Statistical Significance: Not significant (p = 0.115) • Interpretation: Each additional year since earning the highest degree is associated with a $124 decrease in salary, on average, holding other variables constant. This might suggest salary stagnation or negative seniority effect over time, but the result is not significant.</p></li>
</ol>
</section>
<section id="d" class="level6">
<h6 class="anchored" data-anchor-id="d">D</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Assoc"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, salary)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 21038.41    1109.12  18.969  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***
rankProf     5826.40    1012.93   5.752 7.28e-07 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this regression model, the variable rank compares Assistant and Full Professors to the reference group, Associate Professors. The coefficient for rankAsst is -5292.36, indicating that Assistant Professors earn, on average, <code>$</code>5,292 less than Associate Professors, while the coefficient for rankProf is 5826.40, meaning Full Professors earn about <code>$</code>5,826 more than Associate Professors, controlling for other variables in the model. Both coefficients are statistically significant (p &lt; 0.001), suggesting that academic rank is a strong and meaningful predictor of salary, with higher ranks associated with higher pay.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Prof"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, salary)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26864.81    1375.29  19.534  &lt; 2e-16 ***
degreePhD     1388.61    1018.75   1.363    0.180    
rankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***
rankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***
sexFemale     1166.37     925.57   1.260    0.214    
year           476.31      94.91   5.018 8.65e-06 ***
ysdeg         -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this updated regression model, the baseline (reference) rank category is now Full Professor, and the coefficients for rankAssoc and rankAsst represent salary differences relative to Full Professors. The coefficient for rankAssoc is -5826.40, meaning Associate Professors earn <code>$</code>5,826 less than Full Professors on average, while rankAsst is -11,118.76, indicating Assistant Professors earn <code>$</code>11,119 less than Full Professors, all else being equal. Both differences are statistically significant (p &lt; 0.001), reaffirming that academic rank strongly influences salary, with Full Professors earning the most, followed by Associate, then Assistant Professors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">"Asst"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, salary)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this regression output, the baseline category for the rank variable is Assistant Professor. The coefficients for rankAssoc and rankProf represent differences in salary compared to Assistant Professors. The estimate for rankAssoc is 5292.36, meaning Associate Professors earn approximately <code>$</code>5,292 more than Assistant Professors on average, while Full Professors (rankProf) earn about <code>$</code>11,119 more than Assistant Professors. Both coefficients are highly statistically significant (p &lt; 0.001), indicating strong evidence that salary increases with academic rank. This pattern confirms a clear salary hierarchy where Full Professors earn the most, followed by Associate Professors, then Assistant Professors.</p>
</section>
<section id="e" class="level6">
<h6 class="anchored" data-anchor-id="e">E</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, salary)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>By excluding rank, we account for the possibility that women may be underrepresented in higher ranks due to discrimination. If we observe that female faculty earn significantly less than male faculty even after controlling for degree, experience (year), and years since degree (ysdeg) — that strengthens the case for a potential gender-based salary gap. This approach aligns with Finkelstein’s argument: if the process of awarding rank is itself biased, including it in the regression will underestimate the true extent of discrimination in salary. The results show a significant negative association between having a PhD (degreePhD) and salary, with a decrease of approximately <code>$</code>3,299.35 compared to the baseline category (likely Bachelor’s degree). The variable sexFemale is not statistically significant (p = 0.332), indicating no strong evidence of a gender-based salary difference. The variable year is positively associated with salary, with a <code>$</code>351.97 increase for each additional year, and ysdeg (years since degree) has a positive relationship with salary as well, increasing by <code>$</code>339.40 for each additional year since obtaining the degree. The model has a moderate fit, with an R-squared value of 0.6312, meaning about 63.12% of the variability in salary is explained by the predictors. The overall model is statistically significant with an F-statistic of 20.11 (p &lt; 0.001), suggesting that at least one of the predictors is useful in explaining salary.</p>
</section>
<section id="f" class="level6">
<h6 class="anchored" data-anchor-id="f">F</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>new_dean <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> new_dean, <span class="at">data =</span> salary)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + new_dean, 
    data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-3403.3 -1387.0  -167.0   528.2  9233.8 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13328.38    1483.38   8.985 1.33e-11 ***
degreePhD     818.93     797.48   1.027   0.3100    
rankProf    11096.95    1191.00   9.317 4.54e-12 ***
rankAssoc    4972.66     997.17   4.987 9.61e-06 ***
sexFemale     907.14     840.54   1.079   0.2862    
year          434.85      78.89   5.512 1.65e-06 ***
new_dean     2163.46    1072.04   2.018   0.0496 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2362 on 45 degrees of freedom
Multiple R-squared:  0.8594,    Adjusted R-squared:  0.8407 
F-statistic: 45.86 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Multicollinearity is a concern in regression analysis when two or more explanatory variables are highly correlated, which can distort the estimated coefficients and inflate standard errors. In this context, both year (years in current rank) and ysdeg (years since highest degree) are likely to be highly correlated, since faculty typically begin their academic careers soon after earning their degree. Including both variables in the same model could therefore lead to multicollinearity, making it difficult to isolate the individual effect of each predictor. To avoid this issue, we excluded ysdeg from the model and retained year, as it is more directly tied to the salary progression within academic ranks. Regarding the hypothesis that the new Dean offers more generous salaries, the coefficient for new_dean is 2163.46 with a p-value of 0.0496, which is just below the typical 0.05 threshold for statistical significance. This suggests moderate evidence in support of the hypothesis: faculty hired under the new Dean earn, on average, $2,163 more than those hired before, controlling for degree, rank, sex, and years in current rank. Therefore, we find support for the claim that the new Dean has been offering higher salaries to newly hired faculty.</p>
</section>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="a-2" class="level6">
<h6 class="anchored" data-anchor-id="a-2">A</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, house.selling.price)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The regression analysis provides several insights into the relationship between salary and various factors such as degree, rank, sex, year, and years since the degree (ysdeg), as well as their statistical significance. In the first model, the coefficient for degreePhD is -3299.35, which is statistically significant (p = 0.014704), indicating that individuals with a PhD earn, on average, <code>$</code>3,299.35 less than those with lower levels of education, holding other factors constant. The sexFemale coefficient is -1286.54 (p = 0.332209), which is not significant, suggesting no substantial salary difference between male and female employees in this dataset. The year variable has a positive and statistically significant coefficient of 351.97 (p = 0.017185), meaning that salary increases by approximately <code>$</code>351.97 for each additional year of experience. The ysdeg coefficient is 339.40 (p = 0.000114), indicating that salary increases by <code>$</code>339.40 for each additional year since obtaining the degree, and this relationship is statistically significant. In the second model, focusing on the rank, rankAsst and rankProf are significant, with coefficients of -5292.36 (p = 3.22e-05) and 5826.40 (p = 7.28e-07), respectively. This suggests that Assistant Professors earn <code>$</code>5,292.36 less, and Professors earn <code>$</code>5,826.40 more compared to individuals in other ranks. The sexFemale variable remains non-significant with a coefficient of 1166.37 (p = 0.214), while year remains significant with a positive effect on salary (476.31, p &lt; 0.001). The variable ysdeg is not statistically significant in this model (p = 0.115), indicating no strong evidence of a relationship between years since the degree and salary after accounting for rank. For the house price model, Size and New are both statistically significant. Size has a coefficient of 116.132 (p &lt; 2e-16), meaning that for each additional square foot of house size, the price increases by approximately <code>$</code>116.13. The New variable, with a coefficient of 57736.283 (p = 0.00257), indicates that a new house costs, on average, <code>$</code>57,736.28 more than a non-new house. The interaction term Size:New is also significant (61.916, p = 0.00527), suggesting that the price increase associated with house size is higher for new homes compared to non-new ones.</p>
</section>
<section id="b-2" class="level6">
<h6 class="anchored" data-anchor-id="b-2">B</h6>
<p>Based on the regression output, we can report and interpret the prediction equation and derive separate equations for new and not new homes:</p>
<p>Prediction Equation</p>
<p>The regression model is:</p>
<p>Price = beta_0 + beta_1 * Size + beta_2 * New</p>
<p>Plugging in the values from the output:</p>
<p>Price = -40,230.87 + 116.13 * Size + 57,736.28 * New</p>
<p>Interpretation • Intercept (-40,230.87): This is the estimated base price when size = 0 and the house is not new. It has limited practical meaning but is necessary for the equation. • Size (116.13): Each additional square foot increases the selling price by $116.13, regardless of whether the house is new or not. • New (57,736.28): A new house costs on average $57,736.28 more than a non-new house of the same size. This is statistically significant (p = 0.00257).</p>
<p>Separate Equations</p>
<p>For Not New Homes (New = 0):</p>
<p>Price = -40,230.87 + 116.13* Size</p>
<p>For New Homes (New = 1):</p>
<p>Price = -40,230.87 + 116.13 <em>Size + 57,736.28 Price = 17,505.41 + 116.13 </em>Size</p>
<p>So, the difference lies in the intercept (starting price), while the price per square foot remains the same for both. New homes are consistently priced higher by $57,736.28 at any given size.</p>
</section>
<section id="c-2" class="level5">
<h5 class="anchored" data-anchor-id="c-2">C</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="fu">c</span>(<span class="dv">3000</span>, <span class="dv">3000</span>),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>predicted_prices <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, newdata)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>predicted_prices</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
365900.2 308163.9 </code></pre>
</div>
</div>
<section id="d-1" class="level6">
<h6 class="anchored" data-anchor-id="d-1">D</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size<span class="sc">*</span>New, house.selling.price)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New + Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this regression model, the selling price of a house (Price) is predicted based on its size (Size), whether it is new (New), and an interaction between Size and New (Size:New). Here’s the interpretation and significance for each coefficient:</p>
<ol type="1">
<li><p>Intercept (-22227.81, p = 0.15536) • Interpretation: This is the predicted price for a not new home of size 0, which doesn’t have a practical interpretation in this context, but serves as the model’s baseline. • Significance: Not statistically significant (p &gt; 0.05), indicating this intercept does not differ significantly from zero.</p></li>
<li><p>Size (104.44, p &lt; 2e-16) • Interpretation: For homes that are not new, each additional square foot is associated with an increase in price of approximately $104.44. • Significance: Highly significant (p &lt; 0.001), meaning size is a strong predictor of house price.</p></li>
<li><p>New (-78527.50, p = 0.12697) • Interpretation: For a home of size 0, being new decreases the base price by about $78,528 compared to an old home. However, since size 0 isn’t practical, this coefficient alone shouldn’t be interpreted directly. • Significance: Not statistically significant (p &gt; 0.05), so we do not have strong evidence that newness affects price independently when size is zero.</p></li>
<li><p>Interaction: Size*New (61.92, p = 0.00527) • Interpretation: For new homes, each additional square foot increases the price by $61.92 more than it would for old homes. So, for new homes, the total size effect is 104.44 + 61.92 = $166.36 per square foot. • Significance: Statistically significant (p &lt; 0.01), indicating the relationship between size and price differs significantly between new and old homes.</p></li>
</ol>
</section>
<section id="e-1" class="level6">
<h6 class="anchored" data-anchor-id="e-1">E</h6>
<p>The regression model provides separate equations for predicting the selling price of homes based on their size and whether they are new. For new homes, the predicted selling price is given by: Price = 17,505.42 + 116.13 × Size, which includes the base effect of being a new home. For not new homes, the equation is: Price = -40,230.87 + 116.13 × Size. Both types of homes have the same slope, meaning the price increases by about $116.13 for each additional square foot. However, new homes have a higher starting price by about $57,736, reflecting the premium associated with being newly built.</p>
</section>
<section id="f-1" class="level6">
<h6 class="anchored" data-anchor-id="f-1">F</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="fu">c</span>(<span class="dv">3000</span>, <span class="dv">3000</span>),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>predicted_prices <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, newdata)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>predicted_prices</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
398307.5 291087.4 </code></pre>
</div>
</div>
</section>
<section id="g" class="level6">
<h6 class="anchored" data-anchor-id="g">G</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Size =</span> <span class="fu">c</span>(<span class="dv">1500</span>, <span class="dv">1500</span>),</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">New =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>predicted_prices <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, newdata)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>predicted_prices</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
148776.1 134429.8 </code></pre>
</div>
</div>
<p>The predicted selling prices in (F) and (G) show how the price difference between new and not new homes changes with size. At a larger home size (as seen in F), the new home is priced at <code>$</code>398,307.5, while the not new home is <code>$</code>291,087.4, a difference of <code>$</code>107,220.1. In contrast, at a smaller size (as seen in G), the new home is priced at <code>$</code>148,776.1, and the not new home at <code>$</code>134,429.8, a smaller difference of <code>$</code>14,346.3. This shows that as home size increases, the gap in predicted price between new and not new homes becomes much larger. In other words, the price premium for new homes grows with size, suggesting an interaction effect—larger new homes are valued significantly more compared to similarly sized older homes.</p>
</section>
<section id="h" class="level6">
<h6 class="anchored" data-anchor-id="h">H</h6>
<p>The model with the interaction term better represents the relationship between size, new, and the outcome price. In the model without interaction, the effect of size on price is assumed to be the same for both new and not new homes—only the intercept changes based on whether the house is new. However, the interaction model allows the effect of size to differ depending on the home’s condition, which is more realistic. From previous results, we saw that the price difference between new and not new homes grows as size increases, which suggests that the impact of size is not uniform across both categories. This pattern indicates a meaningful interaction: new homes gain more value per additional square foot than not new homes. Therefore, the interaction model is preferred because it captures this changing relationship, leading to more accurate predictions and a better fit to the data when such differences exist.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>